### ISSUE TITLE
Full Stack projektin katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [ollikehy/jafa#3]
# Full Stack projektin katselmointi

Terve @jafa! Tässä lyhyt katselmointi Full Stack kurssin projektistasi. Katselmoinnissa esitetyt kommentit ovat parannusehdotuksia, joita voit _halutessasi_ ottaa huomioon tässä tai tulevissa projekteissasi. Mitään muutoksia tähän projektiin ei siis ole pakko tehdä suoritusmerkintää varten.

### Mitä tein?

- Rekisteröidyin
- Muokkasin profiiliani
- Lisäsin uuden treenin ja yritin poistaa sen
- Hain harjoituksia
- Lisäsin uuden harjoituksen
- Kirjauduin ulos

### Kokemus

- Sovelluksella on selkeä käyttöliittymä, hyvää työtä! 🏆
- Virhetilanteissa näytetään selkeät virheilmoitukset
- Treenin poistamiseen liittyvään pyyntöön tulee palvelimelta 404 vastaus
- Lisätty treeni ei listaudu, kun painaa "View your workouts"-painiketta, vaan vasta kun päivittää sivun tai navigoi "Workouts"-sivulle uudestaan

## Koodi

- Frontend-puolen koodi on selkeästi organisoitua, hyvä!
- Erittäin kattavan oloista e2e-testaamista, mainiota!
- `npm ci`-voisi olla [tässä kohtaa](https://github.com/ollikehy/jafa/blob/master/client/Dockerfile-ci#L7) sopivampi komento.
- [Tätä](https://github.com/ollikehy/jafa/blob/master/client/src/components/app/Header.js#L18) ei tarvita, jos hyödyntää `updateState`-metodissa nuolifunktiota:

```javascript
export class Header extends Component {
  // ...

  updateState = () => {
    // ...
  }

  // ...
}
```

- API-kutsut on abstraktoitu hyvin uudellenkäytettäviksi palveluiksi
- [Luokkien nimet](https://github.com/ollikehy/jafa/blob/master/client/src/redux/apis/exerciseApi.js#L5) kannattaa kirjoittaa isolla alkukirjaimella. Luokan voisi myös toteuttaa ilman staattisia metodeja:

```javascript
class ExerciseApi {
  get(payload) {
    // ...
  }

  // ...
}

const exerciseApi = new ExerciseApi();

export default exerciseApi;
```

- Redux-sagan tuomaa lisäarvoa voisi pohtia. Generaattorit olivat kova sana ennen async/await-syntaksia, mutta tuovatko tässä kontekstissa enää hirveästi lisäarvoa? Voisiko saagoja korvata thunkeilla? Redux-saga on hyvä kirjasto, mutta riippuvuutena raskaampi, kuin esimerkiksi redux-thunk
- Myös backend-puolen koodi on selkeästi organisoitua, hienoa!
- `res.json`- ja `res.send`-kutsujen yhteydessä `toJSON`-metodia ei tarvitse [erikseen kutsua](https://github.com/ollikehy/jafa/blob/master/server/src/controllers/exerciseRouter.js#L26). Kun JSON-muotoinen vastaus muodostetaan, `JSON.stringify`-metodi kutsuu sitä automaattisesti
- Hyviä uudelleenkätettäviä middlewareja 
- Pyyntöjen validointi on toteuttu erinomaisesti
- Voisiko kehityskäytössä olla lokaali MongoDB-tietokanta, esim. [mongo](https://hub.docker.com/_/mongo)-imagen avulla? En ainakaan löytänyt viitteitä siitä [docker-compose.yml](https://github.com/ollikehy/jafa/blob/master/docker-compose.yml)-tiedostosta.

## Kokonaisuus

Käyttökelpoinen sovellus, jossa on selkä käyttöliittymä, eikä suurempia sen käyttöä haittaavia bugeja. Sovelluksen koodi on kaikin puolin järkevästi organisoitua ja sen koodi on pääosin erittäin laadukasta. Testaamista on tehty kattavasti ja dockeria on hyödynnetty järkevästi. Hyvää työtä!

**Comment by ollikehy** [comment]
Kiitos palautteesta! 

* Redux-sagan tuomaa lisäarvoa voisi pohtia
Otin Sagan käyttöön alunperin projektia aloittaessa, sillä minulla oli siitä eniten kokemusta siinä vaiheessa. Syksyllä jatkaessani projektia mietin itse myös sen tarpeellisuutta, mutta panostin mielummin muuhun toiminnallisuuteen kuin sen refaktorointiin. Samasta syystä projektissa on myös luokkakomponentit käytössä hookien sijaan.

* Voisiko kehityskäytössä olla lokaali MongoDB-tietokanta
En olekkaan ennen kuullut lokaalista mongodb-kannasta, mutta sen käyttöönotto testi- ja kehitysympäristöissä olisi huomattavasti luontevampaa.

**Comment by Kaltsoon** [comment]
Eipä kestä!

Hienoa kuulla, että taustalla on ollut tollasta pohdintaa. Harvoin on mitään absoluuttisen parasta ratkaisua (kuten ei tässäkään tilanteessa), mutta oma kokemus on, että "tylsät" ratkaisut on usein aika hyviä. Tietokannat usein asennetaan kehityksen aikana omalle koneella tavalla tai toisella. Docker helpottaa asennusta ja käyttöä huomattavasti esim. ton [mongo](https://hub.docker.com/_/mongo)-imagen avulla.
